### ISSUE TITLE
Unresolved minor issues to fix

### ISSUE THREAD

**Issue by guypaxman** [guypaxman/vbr_bayesian_inversion#18]
- The posterior distribution matrix (Vpo) is not saving properly due to memory issues. I think before I was only saving particular entries from this matrix (i.e. the max likelihood solution, or covariances at the chosen sites only).
- Some functions I believe remain unused (particularly the "...vsonly.m" functions in /inv_functions).
- Is "run_invert_xfit_premelt.m" still needed?
- "generate_parameter_sweep_HL.m" should be renamed to remove Harriet's initials and needs some improved commenting.
- Readme needs updating.

**Comment by chrishavlin** [comment]
The issue saving  `Vpo` is likely related to the new `save_bayes_results` function that I wrote -- that's saving out both the max likelihood subsets and the full `Vpo`. Was it not saving it before? Easiest fix might be to add a flag to `save_bayes_results` so that you can toggle whether or not it saves the full result.

**Comment by chrishavlin** [comment]
I think these are all resolved -- I'll let you close, @guypaxman
